### ISSUE TITLE
No results (Getting text … 100%)

### ISSUE THREAD

**Issue by grahamperrin** [Thomas-QM/BookmarkSearch#3]
Results should appear immediately after the search is complete. For example in Waterfox: 

![2018-05-19 19 47 10 waterfox](https://user-images.githubusercontent.com/192271/40271988-a5b0ef86-5b9d-11e8-85fe-a09595ebc9f4.png)

I waited a long while, no results …

**Comment by canislupaster** [comment]
having the same issue, strange, firefox only

**Comment by canislupaster** [comment]
ok now that this issue is seperated from #4 this "issue" could happen because of rounding up to 100% or it processing onto the next stage after it has completed or the asynchronous methods, so i dont really think this is a bug

**Comment by grahamperrin** [comment]
Not reproducible today. Would you like to close this, to be reopened if necessary? 

Thanks

**Comment by canislupaster** [comment]
:)
