### ISSUE TITLE
Inexplicably long waiting periods

### ISSUE THREAD

**Issue by grahamperrin** [Thomas-QM/BookmarkSearch#4]
With Firefox 60.0.1 (64-bit), a wait of more than half an hour with progress apparently at 99%: 

![2018-05-19 19 58 25](https://user-images.githubusercontent.com/192271/40272500-03f753ca-5ba6-11e8-944e-5cfe3f10fef0.png)

![2018-05-19 20 29 55](https://user-images.githubusercontent.com/192271/40272502-081c4cbc-5ba6-11e8-91da-0d3fcc0dd046.png)

![2018-05-19 20 38 29](https://user-images.githubusercontent.com/192271/40272503-0ae2728c-5ba6-11e8-9ab5-a6aab0c8185e.png)

----

Then I switched from Firefox to Waterfox, found a result of one of the searches that I began before testing Firefox:  

![2018-05-19 20 40 06](https://user-images.githubusercontent.com/192271/40272530-94d99b64-5ba6-11e8-9e5a-977951f44672.png)

To distinguish this issue from #3: 

- #3 is cosmetic, UX; if things are truly complete then there should be no delay
- this issue is performance-oriented.

**Comment by canislupaster** [comment]
found the issue, it was sending a get request to a file download, awaiting the whole string...

**Comment by canislupaster** [comment]
fixed, now sending a header request before getting the text
